build:
	gcc insert_resource.c -o insert_resource
	gcc remove_resource.c -o remove_resource
	gcc switch_state.c -o switch_state
	gcc test_insert_remove.c -o test_insert_remove
	gcc test_open.c -o test_open
	gcc test_state_transition.c -o test_state_transition
	gcc test_truncate.c -o test_truncate
	gcc test_rename.c -o test_rename
	gcc test_mkdir.c -o test_mkdir
	gcc test_rmdir.c -o test_rmdir

clean:
	rm -f insert_resource remove_resource switch_state test_insert_remove test_open test_state_transition test_truncate test_rename test_mkdir test_rmdir