build:
	gcc switch_state.c -o switch_state
	gcc test_all_syscall.c -o test_all_syscall
	gcc test_insert_remove.c -o test_insert_remove
	gcc test_state_transition.c -o test_state_transition

clean:
	rm -f switch_state test_all_syscall test_insert_remove test_state_transition