#!/bin/bash

# Navigate to directory syscall_table_discover
cd syscall_table_discover || { echo "Failed to enter directory syscall_table_discover"; exit 1; }

# Run make
make all || { echo "Make command failed"; exit 1; }

cd ..

# Navigate to directory reference-monitor
cd reference-monitor || { echo "Failed to enter directory reference-monitor"; exit 1; }

# Run make
make all || { echo "Make command failed"; exit 1; }

cd ..

cd singlefile_fs || { echo "Failed to enter directory singlefile_fs"; exit 1; }

# Run make
make all || { echo "Make command failed"; exit 1; }

cd ..

# Navigate to directory test
cd test || { echo "Failed to enter directory test"; exit 1; }

# Run make
make build || { echo "Make command failed"; exit 1; }

echo "Build successful"