#!/bin/bash

# Navigate to directory syscall_table_discover
cd syscall_table_discover || { echo "Failed to enter directory syscall_table_discover"; exit 1; }

# Run make
make mount || { echo "Make command failed"; exit 1; }

cd ..

cd singlefile_fs || { echo "Failed to enter directory singlefile_fs"; exit 1; }

make load-FS-driver || { echo "Make command failed"; exit 1; }

make create-fs || { echo "Make command failed"; exit 1; }

make mount-fs || { echo "Make command failed"; exit 1; }

cd ..

# Navigate to directory reference-monitor
cd reference-monitor || { echo "Failed to enter directory reference-monitor"; exit 1; }

# Run make
make mount  || { echo "Make command failed"; exit 1; }

echo "Mount successful"