//Error codes
#define SUCCESS 0
#define GENERIC_ERR -1 
#define OP_NOT_PERMITTED_ERR -2
#define PASSWD_MISMATCH_ERR -3
#define RES_NOT_PROTECTED_ERR -4
#define INVALID_STATE_ERR -5
#define RES_ALREADY_PROTECTED_ERR -6
#define RES_PATH_RESOLVE_ERR -7